openapi: '3.0.2'
info:
  title: TODO
  version: '1.0'
servers:
  - url: https://api-dev.efullstack.dev/v1
  - url: https://api-qa.efullstack.dev/v1
  - url: https://api.efullstack.dev/v1
paths:
  /todo:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      requestBody:
        description: A JSON object containing todo information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /todo/{id}:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Todo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      requestBody:
        description: A JSON object containing pet information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Todo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      responses:
        '200':
          description: OK
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          example: 1
        name:
          type: string
          example: Pay EMI
        description:
          type: string
          example: House Loan
        dateTime:
          type: string
          pattern: mmddyyyyMMss
          example: 120320231836
        status:
          type: boolean
          example: true
      required:
        - id
        - name
        - dateTime
        - status
    Error:
      type: object
      properties:
        traceId:
          type: string
          example: 1234-xdfgh-e43545-sfewt99
        message:
          type: string
          example: Internal Server Error
        path:
          type: string
          example: /todo
        method:
          type: string
          example: POST
    
    
